services:
  mysql:
    image: mysql:latest
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: gamepickd-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  s3mock:
    image: adobe/s3mock:latest
    container_name: s3mock
    environment:
      - initialBuckets=gamepickd-images
      - root=/s3mock
    ports:
      - "9095:9090"   # host:container  (changed host port!)
      - "9191:9191"
    volumes:
      - s3mock-data:/s3mock
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9095/" ]
      interval: 5s
      timeout: 5s
      retries: 6

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-container
    hostname: dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
    working_dir: /home/dynamodblocal
    volumes:
      - dynamodb-data:/home/dynamodblocal
    healthcheck:
      test: [ "CMD", "bash", "-c", "exec 3<>/dev/tcp/localhost/8000" ]
      interval: 5s
      timeout: 5s
      retries: 5

  dynamodb-setup:
    image: amazon/aws-cli:latest
    container_name: dynamodb-setup
    depends_on:
      dynamodb:
        condition: service_started
    environment:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./init-dynamodb.sh:/init-dynamodb.sh
    entrypoint: [ "/bin/sh", "/init-dynamodb.sh" ]
    profiles:
      - dynamodb-setup
    restart: "no"

volumes:
  mysql-data:
  s3mock-data:
  dynamodb-data: